name: Vercel Production Deployment

# env:
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  vercel-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PNPM
        uses: pnpm/action-setup@v2

      - name: Vercel Build
        run: |
          pnpm install --global vercel
          vercel build

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v20
        with:
          # Github Issue Config
          # github-token: ${{ secrets.GITHUB_TOKEN }
          # github-comment: true

          # Vercel Credentials
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

          # Vercel Configuration
          # working-directory: ./
          vercel-args: --prod --prebuilt --yes


  # Deploy-Production:
  #   runs-on: ubuntu-latest
  #   container: mcr.microsoft.com/devcontainers/javascript-node:16-bullseye
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: pnpm/action-setup@v2

  #     - name: Install Vercel CLI
  #       run: pnpm install --global vercel

  #     - name: Pull Vercel Environment Information
  #       run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

  #     - name: Build Project Artifacts
  #       run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

  #     - name: Deploy Project Artifacts to Vercel
  #       run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}