name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  WORKER_KV_KEY: ${{ secrets.WORKER_KV_KEY }}
  WORKER_ACCOUNT_ID: ${{ secrets.WORKER_ACCOUNT_ID }}
  WORKER_KV_NAMESPACE_ID: ${{ secrets.WORKER_KV_NAMESPACE_ID }}

on:
  push:
    branches:
      - main

jobs:
  vercel-production-deployment:
    runs-on: ubuntu-latest
    environment:
      name: mainnet
      url: https://pokemon-originals-blockops.vercel.app/
    steps:
      - uses: actions/checkout@v2

      - name: Install PNPM
        uses: pnpm/action-setup@v2

      - name: Vercel Production Build
        run: |
          pnpm install --global vercel
          vercel build --cwd apps/dapp --prod

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v20
        with:
          # Vercel Credentials
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

          # Vercel Configuration
          working-directory: apps/dapp
          vercel-args: --prod --prebuilt --yes
